version: "3"

services:
  ansible:
    build: ansible
    tty: true
    working_dir: "/var/data"
    volumes:
      - type: bind
        source: "./ansible/data"
        target: "/var/data"
      - type: bind
        source: "./shared/ssh"
        target: "/root/.ssh"

  target01:
    container_name: target01
    build: target
    tty: true
    volumes:
      - type: bind
        source: "./shared/ssh"
        target: "/root/.ssh"

  target02:
    container_name: target02
    build: target
    tty: true
    volumes:
      - type: bind
        source: "./shared/ssh"
        target: "/root/.ssh"

  mariadb-ansible:
    container_name: mariadb-ansible
    build: db
    volumes:
      - type: bind
        source: "./shared/ssh"
        target: "/root/.ssh"

  nginx-ansible:
    container_name: nginx-ansible
    build: web
    ports:
      - "80:80"
      - "8000:8000"
    volumes:
      - type: bind
        source: "./shared/ssh"
        target: "/root/.ssh"
      - type: bind
        source: "./shared/www/"
        target: "/var/www/"
      - type: bind
        source: "./web/conf.d/"
        target: "/etc/nginx/conf.d/"
    depends_on:
      - php-ansible

  php-ansible:
    container_name: php-ansible
    build: app
    volumes:
      - type: bind
        source: "./shared/ssh"
        target: "/root/.ssh"
      - type: bind
        source: "./shared/www/"
        target: "/var/www/"
